### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by gabrielperales**
Tests were broken because we were trying to test `flipComparison` which was removed in the last commit.

### CODE REVIEW

**Comment by gabrielperales** [comment]
I'm going to keep working on doing some tests, so you can merge it later, or you can merge it know if you want master branch pass all the tests.

**Comment by jackfranklin** [comment]
Ah sorry I was bit eager on merging! I'll leave this be, just ping me when it's ready. Thank you so much!

**Comment by gabrielperales** [comment]
I think you already can merge it.

**Comment by gabrielperales** [comment]
@jackfranklin please, have a look to this merge request :)

**Pull request merged**
